// Contract addresses for different networks
// This file will be auto-generated by the deployment script

export const CONTRACT_ADDRESSES = {
  // Anvil local development
  31337: {
    GLB3D_NFT: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
    NFT_MARKETPLACE: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
  },
  // Add other networks as needed
  // 1: { // Ethereum Mainnet
  //   GLB3D_NFT: "",
  //   NFT_MARKETPLACE: "",
  // },
  // 11155111: { // Sepolia Testnet
  //   GLB3D_NFT: "",
  //   NFT_MARKETPLACE: "",
  // },
} as const;

export type SupportedChainId = keyof typeof CONTRACT_ADDRESSES;

export function getContractAddress(
  chainId: SupportedChainId,
  contract: "GLB3D_NFT" | "NFT_MARKETPLACE"
): `0x${string}` {
  const address = CONTRACT_ADDRESSES[chainId]?.[contract];
  if (!address || address === "0x0000000000000000000000000000000000000000") {
    throw new Error(`Contract ${contract} not deployed on chain ${chainId}`);
  }
  return address as `0x${string}`;
}
